### ISSUE TITLE
error KeyError: '14:593705'

### ISSUE THREAD

**Issue by tiagopradopaim** [AMarete/fimpute-utils#1]
when running snprecode with the files available as test :
./snprecode -g geno_imp.txt -s snp_info.txt -n study_sample_ID.txt -t 2 -a alleles.txt -o teste

I am getting this error: 

----------------------------------------
FImpute helper utility (Version 1.0.3)
Copyright (C) 2018-2021 Andrew Marete
----------------------------------------
checking system requirements...
system requirements met...
Traceback (most recent call last):
  File "/home/polo-ldva/anaconda3/envs/py36/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/polo-ldva/anaconda3/envs/py36/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "./snprecode/__main__.py", line 95, in <module>
  File "./snprecode/__main__.py", line 73, in main
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "./snprecode/fi2geno.py", line 122, in <module>
KeyError: '14:593705'

Have any idea what is the problem?

**Comment by AMarete** [comment]
The error was because snprecode was using the snpname as a key, but the snpname in the alleles.txt file and the imputed snpinfo.txt were different. I have updated the file and created a new executable to resolve the error. Now it will use the chrom_pos as a unique identifier. If the issue persists, let me know, and thank you for notifying me of the error.
You can redownload the executable using the README instructions and try to rerun it.
